version: '3'

services:

  capstone_db:
    image: postgres:latest
    container_name: capstone_db_prod
    environment:
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - capstone_be

  capstone_api:
    image: jayaanim/capstone_api:latest
    container_name: capstone_api_prod
    restart: always
    networks:
      - capstone_be
      - capstone_fe
    depends_on:
      - capstone_db

  # We will need to make a FE container here

  capstone_proxy:
    image: nginx:latest
    container_name: capstone_proxy_prod
    environment:
      - DOMAIN=${DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
    volumes:
      - ../nginx/templates:/etc/nginx/templates
      - ../nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../ssl_certs:/ssl_certs
    ports:
      - 80:80
      - 443:443
    restart: always 
    networks:
      - capstone_fe
    depends_on:
      - capstone_api

networks:    
  capstone_fe:
    driver: bridge
  capstone_be:
    driver: bridge

volumes:
  dbdata:
