version: '3'

services:

  capstone_db:
    image: postgres:latest
    container_name: capstone_db_prod
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - capstone_be
    environment:
      - POSTGRES_PASSWORD=password

  capstone_api:
    image: jayaanim/capstone_api:latest
    container_name: capstone_api_prod
    restart: always
    volumes:
      - api_static:/static
      - api_media:/media
    networks:
      - capstone_be
      - capstone_fe
    depends_on:
      - capstone_db

  # We will need to make a FE container here

  capstone_proxy:
    image: nginx:latest
    container_name: capstone_proxy_prod
    restart: always
    volumes:
      - ../nginx/templates:/etc/nginx/templates
      - ../nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /root/capstone_api_deploy/ssl_certs:/ssl_certs
      - api_static:/etc/static
      - api_media:/etc/media
    networks:
      - capstone_fe
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=${DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
    depends_on:
      - capstone_api

networks:    
  capstone_fe:
    driver: bridge
  capstone_be:
    driver: bridge

volumes:
  db_data:
  api_static:
  api_media:
