version: '3'

services:

  capstone_db:
    image: postgres:latest
    container_name: capstone_db_dev
    environment:
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - capstone_be

  capstone_api:
    build: ../api/
    container_name: capstone_api_dev
    restart: always
    networks:
      - capstone_fe
      - capstone_be
    depends_on:
      - capstone_db

  # We will need to make a FE container here

  capstone_proxy:
    image: nginx:latest
    container_name: capstone_proxy_dev
    volumes:
      - ../nginx/dev_templates:/etc/nginx/templates
      - ../nginx/dev_conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: always 
    networks:
      - capstone_fe
    depends_on:
      - capstone_api

networks:    
  capstone_fe:
    driver: bridge
  capstone_be:
    driver: bridge

volumes:
  dbdata:
