# Generated by Django 5.0.2 on 2024-03-25 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('max_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('min_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('max_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('shopping_mall', models.BooleanField(default=False)),
                ('zoo', models.BooleanField(default=False)),
                ('museum', models.BooleanField(default=False)),
                ('night_club', models.BooleanField(default=False)),
                ('park', models.BooleanField(default=False)),
                ('casino', models.BooleanField(default=False)),
                ('art_gallery', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('campground', models.BooleanField(default=False)),
                ('cafe', models.BooleanField(default=False)),
                ('amusement_park', models.BooleanField(default=False)),
                ('landmark', models.BooleanField(default=False)),
                ('point_of_interest', models.BooleanField(default=False)),
                ('store', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('meal_takeaway', models.BooleanField(default=False)),
                ('tourist_attraction', models.BooleanField(default=False)),
            ],
        ),
    ]
